### ISSUE TITLE
chown -R www-data: on run.sh

### ISSUE THREAD

**Issue by julianxhokaxhiu** [runningman84/docker-rainloop#1]
Hi,

can you please move [this](https://github.com/runningman84/docker-rainloop/blob/master/Dockerfile#L27) line into the `run.sh` file?

I'm trying to use to attach a volume, but Rainloop returns

```
[202] Data folder permissions error [is_writable]
```

If I exec inside the docker, and I manually do the chown command, then it works. Probably if we do it inside the run.sh for sure we fix it.

Thank you in advance,
Julian

**Comment by runningman84** [comment]
yes please check this:
https://github.com/runningman84/docker-rainloop/commit/8c72d712d5db66d82f45027b0a4b0e842e2037bd
it should trigger a docker build soon

**Comment by julianxhokaxhiu** [comment]
Thank you very much, tested and works! Well done :D
