### ISSUE TITLE
PHP Upload size is too low - increase to 20MB

### ISSUE THREAD

**Issue by julianxhokaxhiu** [runningman84/docker-rainloop#2]
Hi,

I noticed that the current file size restrictions are this ones:

```
PHP: upload_max_filesize = 2M; post_max_size = 8M
```

what I suggest is to enhance this one by enlarging it to

```
PHP: upload_max_filesize = 20M; post_max_size = 40M
```

Maybe if we could set this up using environments variable would be awesome!

Thanks in advance,
Julian

**Comment by runningman84** [comment]
fixed with
https://github.com/runningman84/docker-rainloop/commit/d0ab126acca83bcb5d37cb952f7266c9035afcec
