### ISSUE TITLE
Download Link seems outdated

### ISSUE THREAD

**Issue by setiseta** [runningman84/docker-rainloop#4]
Hello,

it seems that the download link of the rainloop-latest ist outdated.
It gets an old version.
I think it should be: http://www.rainloop.net/repository/owncloud/rainloop.zip
(AGPLv3 edition)

Would be nice if you can updated this.

Kind regards,
Sebastian

**Comment by runningman84** [comment]
Please create a pull request. Am 22.03.2017 12:45 nachm. schrieb Seti <notifications@github.com>:Hello,
it seems that the download link of the rainloop-latest ist outdated.
It gets an old version.
I think it should be: http://www.rainloop.net/repository/owncloud/rainloop.zip
(AGPLv3 edition)
Would be nice if you can updated this.
Kind regards,
Sebastian

**Comment by setiseta** [comment]
Hello,

I have created a Pull Request #5 for this.
It would be nice if you merge this.

Best regards,
Sebastian

**Comment by runningman84** [comment]
Thanks!
