### ISSUE TITLE
Change Default Password

### ISSUE THREAD

**Issue by hechi** [runningman84/docker-rainloop#6]
Hey @runningman84 ,

thx to provide a nice docker image on docker hub. I have a little problem when i change the default password from 12345 to something else via the "RAINLOOP_ADMIN_PASSWORD". It will not be accepted in the web interface. This is because only 12345 is working unsalted (https://github.com/RainLoop/rainloop-webmail/issues/28). 

Servus

**Comment by runningman84** [comment]
Hi @hechi, that's a good catch. Feel free to test my latest image which should use the rainloop api to change the password...

**Comment by hechi** [comment]
@runningman84 cool thanks i will test it
