### ISSUE TITLE
Logged into admin, and just a spinning wheel

### ISSUE THREAD

**Issue by wicadmin** [runningman84/docker-rainloop#8]
No cgate as yet, just rainloop at the moment.

**Comment by runningman84** [comment]
Rainloop works just fine for me. Are there any errors in the docker container log?

**Comment by wicadmin** [comment]
I got it to work. Ultimately, it proved too slow for me to use. Does using it with an email server pre-download gmail messages thereby making it fast?

**Comment by runningman84** [comment]
with a local email server like the cgate container it is quite fast for me.

**Comment by wicadmin** [comment]
Does cgate pre-download the messages or just proxies to the gmail servers?
