### ISSUE TITLE
container doesn't start with ubuntu 18.04

### ISSUE THREAD

**Issue by cyrale** [runningman84/docker-rainloop#9]
When you launch a container with the latest version, this error was displayed `sed: can't read /etc/php/7.0/apache2/php.ini: No such file or directory`.

The file is now in the yolo directory : `/etc/php/7.2/apache2/php.ini`

**Comment by runningman84** [comment]
Thanks for the hint, it should be fixed with this commit:
https://github.com/runningman84/docker-rainloop/commit/0723559fd442cace33cce48a8cca202299420a80
